name: build
on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında çalışır
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  tag-and-release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine latest version and build number
        id: version
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+-build\.[0-9]+$' | head -n 1 || echo "")
          
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="v1.0.0-build.1"
          else
            BASE_VERSION=$(echo "$LATEST_TAG" | cut -d':' -f1)
            BUILD_NUMBER=$(echo "$LATEST_TAG" | cut -d'.' -f2)
            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
            NEW_TAG="${BASE_VERSION}-build.${NEW_BUILD_NUMBER}"
          fi
          
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          echo "New Tag: $NEW_TAG"

      - name: Create and push new tag
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_tag }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
